'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace ErrorLogEF

    Partial Public Class DB_ErrorLogEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=DB_ErrorLogEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Table_ErrorLog() As DbSet(Of Table_ErrorLog)
    
    End Class

End Namespace
