'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ErrorLogEF

    Partial Public Class Table_ErrorLog
        Public Property ErrorID As Integer
        Public Property URL As String
        Public Property UserName As String
        Public Property UserEmail As String
        Public Property ExceptionType As String
        Public Property Message As String
        Public Property ErrorHTML As String
        Public Property ErrorTime As Nullable(Of Date)
        Public Property ip_adress As String
    
    End Class

End Namespace
