'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace VisitorsLog.db

    Partial Public Class VisitorsLogEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=VisitorsLogEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Table_VisitorLogs() As DbSet(Of Table_VisitorLogs)
    
    End Class

End Namespace
