'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace VisitorsLog.db

    Partial Public Class Table_VisitorLogs
        Public Property Id As Integer
        Public Property UserName As String
        Public Property PageName As String
        Public Property VisitTime As Nullable(Of Date)
        Public Property IpAdress As String
        Public Property Country As String
        Public Property BrowserType As String
        Public Property BrowserPlatform As String
    
    End Class

End Namespace
