'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class aspnet_Roles
        Public Property ApplicationId As System.Guid
        Public Property RoleId As System.Guid
        Public Property RoleName As String
        Public Property LoweredRoleName As String
        Public Property Description As String
    
        Public Overridable Property aspnet_UsersInRoles As ICollection(Of aspnet_UsersInRoles) = New HashSet(Of aspnet_UsersInRoles)
        Public Overridable Property aspnet_UsersInRoles1 As ICollection(Of aspnet_UsersInRoles) = New HashSet(Of aspnet_UsersInRoles)
    
    End Class

End Namespace
