'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class aspnet_UsersInRoles
        Public Property UserId As System.Guid
        Public Property RoleId As System.Guid
    
        Public Overridable Property aspnet_Roles As aspnet_Roles
        Public Overridable Property aspnet_Roles1 As aspnet_Roles
        Public Overridable Property aspnet_Users As aspnet_Users
        Public Overridable Property aspnet_Users1 As aspnet_Users
    
    End Class

End Namespace
