'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class aspnet_Users
        Public Property ApplicationId As System.Guid
        Public Property UserId As System.Guid
        Public Property UserName As String
        Public Property LoweredUserName As String
        Public Property MobileAlias As String
        Public Property IsAnonymous As Boolean
        Public Property LastActivityDate As Date
        Public Property flag As String
        Public Property AccessToAllProjects As Nullable(Of Boolean)
        Public Property SendEmailPaymentReq As Nullable(Of Boolean)
        Public Property SendEmailApproval As Nullable(Of Boolean)
        Public Property SendEmailContract As Nullable(Of Boolean)
        Public Property SendEmailPayments As Nullable(Of Boolean)
        Public Property SendEmailDailyReport As Nullable(Of Boolean)
        Public Property SendEmailWeeklyProjectSummary As Nullable(Of Boolean)
        Public Property SendEmailPendingFollow As Nullable(Of Boolean)
        Public Property SendEmailPaymentsSinceJan As Nullable(Of Boolean)
        Public Property SendEmailClientContracts As Nullable(Of Boolean)
        Public Property Rank As Nullable(Of Integer)
        Public Property Vote_Xmas As Nullable(Of Boolean)
        Public Property Vote_Time As Nullable(Of Date)
        Public Property SendInvitation As Nullable(Of Boolean)
        Public Property PasswordKnown As Nullable(Of Boolean)
        Public Property ApproveFramePo As Nullable(Of Boolean)
        Public Property ContractGirlApprovalEmail As Nullable(Of Boolean)
        Public Property Position As String
        Public Property AuthorizedForExceptionalApprove As Nullable(Of Boolean)
        Public Property AuthorizedForPaymentRequest As Nullable(Of Boolean)
        Public Property SendNotificationInsuranceUpdate As Nullable(Of Boolean)
    
        Public Overridable Property aspnet_Membership As aspnet_Membership
        Public Overridable Property aspnet_Membership1 As aspnet_Membership
        Public Overridable Property aspnet_UsersInRoles As ICollection(Of aspnet_UsersInRoles) = New HashSet(Of aspnet_UsersInRoles)
        Public Overridable Property aspnet_UsersInRoles1 As ICollection(Of aspnet_UsersInRoles) = New HashSet(Of aspnet_UsersInRoles)
    
    End Class

End Namespace
