'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Namespace PTS_MERCURY.db

    Partial Public Class SQL2008_794282_mercuryEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=SQL2008_794282_mercuryEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property aspnet_Membership() As DbSet(Of aspnet_Membership)
        Public Overridable Property aspnet_Roles() As DbSet(Of aspnet_Roles)
        Public Overridable Property aspnet_Users() As DbSet(Of aspnet_Users)
        Public Overridable Property aspnet_UsersInRoles() As DbSet(Of aspnet_UsersInRoles)
        Public Overridable Property Table_Addendum_UserRemarks() As DbSet(Of Table_Addendum_UserRemarks)
        Public Overridable Property Table_Addendums_ClientAdditional() As DbSet(Of Table_Addendums_ClientAdditional)
        Public Overridable Property Table_Approval_PositionEmployee() As DbSet(Of Table_Approval_PositionEmployee)
        Public Overridable Property Table_Approval_Scenario() As DbSet(Of Table_Approval_Scenario)
        Public Overridable Property Table_Approval_Scn_Prj_Users() As DbSet(Of Table_Approval_Scn_Prj_Users)
        Public Overridable Property Table_Approval_UserPositionPrjJunction() As DbSet(Of Table_Approval_UserPositionPrjJunction)
        Public Overridable Property Table_Approval_UserRolePrjectJunction() As DbSet(Of Table_Approval_UserRolePrjectJunction)
        Public Overridable Property Table_ApprUserExcpAccessToActiveUsers() As DbSet(Of Table_ApprUserExcpAccessToActiveUsers)
        Public Overridable Property Table_Contract_Addendum_TimeLimitApprovals() As DbSet(Of Table_Contract_Addendum_TimeLimitApprovals)
        Public Overridable Property Table_Contract_CommentsRead() As DbSet(Of Table_Contract_CommentsRead)
        Public Overridable Property Table_Contract_ProjectIDforClient() As DbSet(Of Table_Contract_ProjectIDforClient)
        Public Overridable Property Table_ContractControlExceptional() As DbSet(Of Table_ContractControlExceptional)
        Public Overridable Property Table_Contracts_ClientAdditional() As DbSet(Of Table_Contracts_ClientAdditional)
        Public Overridable Property Table_Contracts_UserRemarks() As DbSet(Of Table_Contracts_UserRemarks)
        Public Overridable Property Table_Delivery_MatchingIndexes() As DbSet(Of Table_Delivery_MatchingIndexes)
        Public Overridable Property Table_PaymentRequest_OverHeadCheck() As DbSet(Of Table_PaymentRequest_OverHeadCheck)
        Public Overridable Property Table_PO_Akt() As DbSet(Of Table_PO_Akt)
        Public Overridable Property Table_PO_Akt_To_Nak() As DbSet(Of Table_PO_Akt_To_Nak)
        Public Overridable Property Table_PO_Nakladnaya() As DbSet(Of Table_PO_Nakladnaya)
        Public Overridable Property Table_Survey_OfficeParty() As DbSet(Of Table_Survey_OfficeParty)
        Public Overridable Property Table_UserPhotos() As DbSet(Of Table_UserPhotos)
        Public Overridable Property Table1_ProjectInsurCertf() As DbSet(Of Table1_ProjectInsurCertf)
        Public Overridable Property Table3_Invoice() As DbSet(Of Table3_Invoice)
        Public Overridable Property Table3_Invoice_AdditionalApprovalProjectUserMatrix() As DbSet(Of Table3_Invoice_AdditionalApprovalProjectUserMatrix)
        Public Overridable Property Table3_Invoice_AdditionalUserApprovals() As DbSet(Of Table3_Invoice_AdditionalUserApprovals)
        Public Overridable Property Table3_Invoice_PDF() As DbSet(Of Table3_Invoice_PDF)
        Public Overridable Property Table3_Invoice_PRrequestToPM() As DbSet(Of Table3_Invoice_PRrequestToPM)
        Public Overridable Property Table4_PaymentRequest() As DbSet(Of Table4_PaymentRequest)
        Public Overridable Property Table5_PayLog() As DbSet(Of Table5_PayLog)
        Public Overridable Property Table6_Supplier() As DbSet(Of Table6_Supplier)
        Public Overridable Property Table_Contract_Offers() As DbSet(Of Table_Contract_Offers)
        Public Overridable Property Table_Contract_User_Junction() As DbSet(Of Table_Contract_User_Junction)
        Public Overridable Property Table_Contracts_Common() As DbSet(Of Table_Contracts_Common)
        Public Overridable Property Table1_InsurPolicyDocs() As DbSet(Of Table1_InsurPolicyDocs)
        Public Overridable Property Table6_SupplierDetails() As DbSet(Of Table6_SupplierDetails)
        Public Overridable Property AddendumMissingApprovalBreakdowns() As DbSet(Of AddendumMissingApprovalBreakdown)
        Public Overridable Property ContractMissingApprovalBreakdowns() As DbSet(Of ContractMissingApprovalBreakdown)
        Public Overridable Property Notf_AddendumCommentsFromToWhomMatrix() As DbSet(Of Notf_AddendumCommentsFromToWhomMatrix)
        Public Overridable Property Notf_AddendumCommentsUnRead() As DbSet(Of Notf_AddendumCommentsUnRead)
        Public Overridable Property Notf_ContractCommentsFromToWhomMatrix() As DbSet(Of Notf_ContractCommentsFromToWhomMatrix)
        Public Overridable Property Notf_ContractCommentsUnRead() As DbSet(Of Notf_ContractCommentsUnRead)
        Public Overridable Property View_CheckTolerance() As DbSet(Of View_CheckTolerance)
        Public Overridable Property View_AddendumDetails() As DbSet(Of View_AddendumDetails)
        Public Overridable Property View_ContractDetails() As DbSet(Of View_ContractDetails)
        Public Overridable Property View_GetFullUserNameFromUserName() As DbSet(Of View_GetFullUserNameFromUserName)
        Public Overridable Property View_PaymentRequestApprovalStatus() As DbSet(Of View_PaymentRequestApprovalStatus)
        Public Overridable Property View_PendingListRev1() As DbSet(Of View_PendingListRev1)
        Public Overridable Property Table7_CostDivision() As DbSet(Of Table7_CostDivision)
        Public Overridable Property Table7_CostDivision2() As DbSet(Of Table7_CostDivision2)
        Public Overridable Property View_CostCodeSummary0() As DbSet(Of View_CostCodeSummary0)
        Public Overridable Property Table_Budget() As DbSet(Of Table_Budget)
        Public Overridable Property Table2_PONo() As DbSet(Of Table2_PONo)
        Public Overridable Property Table7_CostCode() As DbSet(Of Table7_CostCode)
        Public Overridable Property Table_Addendum_UsersApprv_IgnoreUser() As DbSet(Of Table_Addendum_UsersApprv_IgnoreUser)
        Public Overridable Property Table_Contract_UsersApprv_IgnoreUser() As DbSet(Of Table_Contract_UsersApprv_IgnoreUser)
        Public Overridable Property Table_Addendums() As DbSet(Of Table_Addendums)
        Public Overridable Property Table_Contracts() As DbSet(Of Table_Contracts)
        Public Overridable Property Table1_Project() As DbSet(Of Table1_Project)
        Public Overridable Property Table_Contracts_IgnoreSearchFeed() As DbSet(Of Table_Contracts_IgnoreSearchFeed)
        Public Overridable Property Table_SupplierType() As DbSet(Of Table_SupplierType)
        Public Overridable Property Table_SupplierType_Junction() As DbSet(Of Table_SupplierType_Junction)
        Public Overridable Property Table_SupplierType_Tags() As DbSet(Of Table_SupplierType_Tags)
        Public Overridable Property Table8_ExchangeRates() As DbSet(Of Table8_ExchangeRates)
        Public Overridable Property View_Contract_Addendum_NotApprovedPersonsForEmailNotification() As DbSet(Of View_Contract_Addendum_NotApprovedPersonsForEmailNotification)
        Public Overridable Property Table3_Invoice_Type() As DbSet(Of Table3_Invoice_Type)
        Public Overridable Property Table3_Invoice_Type_Junction() As DbSet(Of Table3_Invoice_Type_Junction)
        Public Overridable Property View_ContractsAddendumsNonExecutedTotal() As DbSet(Of View_ContractsAddendumsNonExecutedTotal)
        Public Overridable Property View_FrameContractsBudgetStatus() As DbSet(Of View_FrameContractsBudgetStatus)
        Public Overridable Property Table_BudgetChangeLog() As DbSet(Of Table_BudgetChangeLog)
        Public Overridable Property Table_Budget_PlannedToSpendConstraints() As DbSet(Of Table_Budget_PlannedToSpendConstraints)
        Public Overridable Property Table1_Project_LawyersCanEnterContract() As DbSet(Of Table1_Project_LawyersCanEnterContract)
        Public Overridable Property BodyTexts() As DbSet(Of BodyText)
        Public Overridable Property Table_Addendum_UsersApprv() As DbSet(Of Table_Addendum_UsersApprv)
        Public Overridable Property Table_Contract_UsersApprv() As DbSet(Of Table_Contract_UsersApprv)
        Public Overridable Property View_SupplierNamesForContracts() As DbSet(Of View_SupplierNamesForContracts)
        Public Overridable Property View_ContractFilesMoveDOC() As DbSet(Of View_ContractFilesMoveDOC)
        Public Overridable Property Table_Required() As DbSet(Of Table_Required)
        Public Overridable Property View_WhatToBePaidRevised() As DbSet(Of View_WhatToBePaidRevised)
    
        Public Overridable Function GetPoNoFromMakerNewGeneration(projectID As Nullable(Of Integer)) As ObjectResult(Of String)
            Dim projectIDParameter As ObjectParameter = If(projectID.HasValue, New ObjectParameter("ProjectID", projectID), New ObjectParameter("ProjectID", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("GetPoNoFromMakerNewGeneration", projectIDParameter)
        End Function
    
        Public Overridable Function sp_FrameContractBudgetPoDetails(frameContractId As Nullable(Of Integer), toleranceLimit As Nullable(Of Decimal), oldValue As Nullable(Of Decimal), newValue As Nullable(Of Decimal)) As ObjectResult(Of sp_FrameContractBudgetPoDetails_Result1)
            Dim frameContractIdParameter As ObjectParameter = If(frameContractId.HasValue, New ObjectParameter("FrameContractId", frameContractId), New ObjectParameter("FrameContractId", GetType(Integer)))
    
            Dim toleranceLimitParameter As ObjectParameter = If(toleranceLimit.HasValue, New ObjectParameter("ToleranceLimit", toleranceLimit), New ObjectParameter("ToleranceLimit", GetType(Decimal)))
    
            Dim oldValueParameter As ObjectParameter = If(oldValue.HasValue, New ObjectParameter("OldValue", oldValue), New ObjectParameter("OldValue", GetType(Decimal)))
    
            Dim newValueParameter As ObjectParameter = If(newValue.HasValue, New ObjectParameter("NewValue", newValue), New ObjectParameter("NewValue", GetType(Decimal)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_FrameContractBudgetPoDetails_Result1)("sp_FrameContractBudgetPoDetails", frameContractIdParameter, toleranceLimitParameter, oldValueParameter, newValueParameter)
        End Function
    
        Public Overridable Function SP_MissingApprovalsOnContractsAndAddendums(username As String) As ObjectResult(Of SP_MissingApprovalsOnContractsAndAddendums_Result)
            Dim usernameParameter As ObjectParameter = If(username IsNot Nothing, New ObjectParameter("username", username), New ObjectParameter("username", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_MissingApprovalsOnContractsAndAddendums_Result)("SP_MissingApprovalsOnContractsAndAddendums", usernameParameter)
        End Function
    
        Public Overridable Function SP_EmailListEverybodyApprovedAddendum(contractId As Nullable(Of Integer)) As ObjectResult(Of String)
            Dim contractIdParameter As ObjectParameter = If(contractId.HasValue, New ObjectParameter("ContractId", contractId), New ObjectParameter("ContractId", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("SP_EmailListEverybodyApprovedAddendum", contractIdParameter)
        End Function
    
        Public Overridable Function SP_EmailListEverybodyApprovedContract(contractId As Nullable(Of Integer)) As ObjectResult(Of String)
            Dim contractIdParameter As ObjectParameter = If(contractId.HasValue, New ObjectParameter("ContractId", contractId), New ObjectParameter("ContractId", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("SP_EmailListEverybodyApprovedContract", contractIdParameter)
        End Function
    
        Public Overridable Function SP_EmailListLawyersApprovedAddendum(addendumId As Nullable(Of Integer)) As ObjectResult(Of String)
            Dim addendumIdParameter As ObjectParameter = If(addendumId.HasValue, New ObjectParameter("AddendumId", addendumId), New ObjectParameter("AddendumId", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("SP_EmailListLawyersApprovedAddendum", addendumIdParameter)
        End Function
    
        Public Overridable Function SP_EmailListLawyersApprovedContract(contractId As Nullable(Of Integer)) As ObjectResult(Of String)
            Dim contractIdParameter As ObjectParameter = If(contractId.HasValue, New ObjectParameter("ContractId", contractId), New ObjectParameter("ContractId", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("SP_EmailListLawyersApprovedContract", contractIdParameter)
        End Function
    
        Public Overridable Function ApprovalStatusContractEF(contractID As Nullable(Of Integer)) As ObjectResult(Of ApprovalStatusContractEF_Result)
            Dim contractIDParameter As ObjectParameter = If(contractID.HasValue, New ObjectParameter("ContractID", contractID), New ObjectParameter("ContractID", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ApprovalStatusContractEF_Result)("ApprovalStatusContractEF", contractIDParameter)
        End Function
    
        Public Overridable Function ApprovalStatusContractAllApprovedEF(contractID As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
            Dim contractIDParameter As ObjectParameter = If(contractID.HasValue, New ObjectParameter("ContractID", contractID), New ObjectParameter("ContractID", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("ApprovalStatusContractAllApprovedEF", contractIDParameter)
        End Function
    
        Public Overridable Function ApprovalStatusAddendumEF(addendumId As Nullable(Of Integer)) As ObjectResult(Of ApprovalStatusAddendumEF_Result)
            Dim addendumIdParameter As ObjectParameter = If(addendumId.HasValue, New ObjectParameter("AddendumId", addendumId), New ObjectParameter("AddendumId", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ApprovalStatusAddendumEF_Result)("ApprovalStatusAddendumEF", addendumIdParameter)
        End Function
    
        Public Overridable Function ApprovalStatusAddendumAllApprovedEF(addendumId As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
            Dim addendumIdParameter As ObjectParameter = If(addendumId.HasValue, New ObjectParameter("AddendumId", addendumId), New ObjectParameter("AddendumId", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("ApprovalStatusAddendumAllApprovedEF", addendumIdParameter)
        End Function
    
        Public Overridable Function sp_DDLProjectsPOCreate(userName As String) As ObjectResult(Of sp_DDLProjectsPOCreate_Result)
            Dim userNameParameter As ObjectParameter = If(userName IsNot Nothing, New ObjectParameter("UserName", userName), New ObjectParameter("UserName", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_DDLProjectsPOCreate_Result)("sp_DDLProjectsPOCreate", userNameParameter)
        End Function
    
        Public Overridable Function sp_DDLCostCodePOCreate(projectID As Nullable(Of Integer), userName As String) As ObjectResult(Of sp_DDLCostCodePOCreate_Result)
            Dim projectIDParameter As ObjectParameter = If(projectID.HasValue, New ObjectParameter("ProjectID", projectID), New ObjectParameter("ProjectID", GetType(Integer)))
    
            Dim userNameParameter As ObjectParameter = If(userName IsNot Nothing, New ObjectParameter("UserName", userName), New ObjectParameter("UserName", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_DDLCostCodePOCreate_Result)("sp_DDLCostCodePOCreate", projectIDParameter, userNameParameter)
        End Function
    
        Public Overridable Function sp_DDLRequestedByPOCreate(projectID As Nullable(Of Integer)) As ObjectResult(Of sp_DDLRequestedByPOCreate_Result)
            Dim projectIDParameter As ObjectParameter = If(projectID.HasValue, New ObjectParameter("ProjectID", projectID), New ObjectParameter("ProjectID", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_DDLRequestedByPOCreate_Result)("sp_DDLRequestedByPOCreate", projectIDParameter)
        End Function
    
    End Class

End Namespace
