'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Notf_ContractCommentsUnRead
        Public Property C_or_A As String
        Public Property C_or_A_id As Integer
        Public Property id_comment As Integer
        Public Property FromWho As String
        Public Property ForWho As String
    
    End Class

End Namespace
