'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_PO_Akt_To_Nak
        Public Property ID_Akt_To_Nak As Integer
        Public Property ID_Nak As Integer
        Public Property AktNo As String
        Public Property Akt_Date As Date
        Public Property Akt_Rub_WithVAT As Decimal
        Public Property CreatedBy As Nullable(Of Date)
        Public Property PersonCreated As String
        Public Property payreqno As Nullable(Of Integer)
        Public Property Comment As String
    
        Public Overridable Property Table_PO_Nakladnaya As Table_PO_Nakladnaya
    
    End Class

End Namespace
