'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table4_PaymentRequest
        Public Property PayReqNo As Integer
        Public Property SiteRecordNo As String
        Public Property ActivityCode As String
        Public Property InvoiceID As Integer
        Public Property PayReqDate As Date
        Public Property Notes As String
        Public Property LinkToInvoice As String
        Public Property Urgency As String
        Public Property Approved As String
        Public Property PersonApprove As String
        Public Property LastAction As Nullable(Of Date)
        Public Property CreatedBy As Nullable(Of Date)
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property DeletedBy As Nullable(Of Date)
        Public Property PersonCreated As String
        Public Property PersonUpdated As String
        Public Property PersonDeleted As String
        Public Property FromAccess As Nullable(Of Integer)
        Public Property AttachmentChange As Nullable(Of Boolean)
        Public Property AttachmentChangeWhen As Nullable(Of Date)
        Public Property PersonChangedAttachment As String
        Public Property PaymentTerm As Nullable(Of Date)
        Public Property AttachmentExist As Nullable(Of Boolean)
        Public Property PersonResponsibleID As Nullable(Of Short)
        Public Property Transport As Nullable(Of Boolean)
        Public Property ContractReference As String
        Public Property Priority As Nullable(Of Short)
        Public Property ToList As Nullable(Of Boolean)
        Public Property ApproveNewGen As Nullable(Of Boolean)
        Public Property PrintPDF As Nullable(Of Boolean)
    
        Public Overridable Property Table3_Invoice As Table3_Invoice
        Public Overridable Property Table5_PayLog As Table5_PayLog
    
    End Class

End Namespace
