'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Contracts
        Public Property ContractID As Integer
        Public Property ProjectID As Short
        Public Property PO_No As String
        Public Property ContractNo As String
        Public Property ContractDate As Nullable(Of Date)
        Public Property ContractValue_woVAT As Nullable(Of Decimal)
        Public Property ContractValue_withVAT As Nullable(Of Decimal)
        Public Property VATpercent As Nullable(Of Short)
        Public Property CostCode As String
        Public Property ContractCurrency As String
        Public Property SupplierID As String
        Public Property ContractDescription As String
        Public Property ContractType As String
        Public Property LinkToTemplatefile_DOC As String
        Public Property SentToSupplier As Nullable(Of Boolean)
        Public Property SignBySupplier As Nullable(Of Boolean)
        Public Property SignByMercury As Nullable(Of Boolean)
        Public Property CollectionBySupplier As Nullable(Of Boolean)
        Public Property ContractGivenTo As String
        Public Property LinkToPDFcopy As String
        Public Property ArchivedByMercury As Nullable(Of Boolean)
        Public Property CreatedBy As Nullable(Of Date)
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property DeletedBy As Nullable(Of Date)
        Public Property PersonCreated As String
        Public Property PersonUpdated As String
        Public Property PersonDeleted As String
        Public Property RequestedBy As String
        Public Property Retention As Nullable(Of Decimal)
        Public Property Note As String
        Public Property AttachmentExist As Nullable(Of Boolean)
        Public Property Scenario As Short
        Public Property Penalties As Boolean
        Public Property PenaltiesNote As String
        Public Property PenaltiesToSupplier As Boolean
        Public Property PenaltiesToSupplierNote As String
        Public Property Budget As Nullable(Of Decimal)
        Public Property BudgetLinkToPDF As String
        Public Property Advance As Nullable(Of Decimal)
        Public Property Interim As Nullable(Of Decimal)
        Public Property Shipment As Nullable(Of Decimal)
        Public Property Delivery As Nullable(Of Decimal)
        Public Property StartDate As Nullable(Of Date)
        Public Property FinishDate As Nullable(Of Date)
        Public Property DeliveryTerms As String
        Public Property GuaranteePeriod As String
        Public Property Nominated As Boolean
        Public Property FrameContract As Boolean
        Public Property POexecuted As Boolean
        Public Property Exceptional As Nullable(Of Boolean)
        Public Property NominatedApprovedByESTM As Short
        Public Property NominatedWhenApprovedByESTM As Nullable(Of Date)
        Public Property LinkToTemplatefile_DOCBackUp As String
        Public Property LinkToPDFcopyBackUp As String
    
        Public Overridable Property Table_Addendums As ICollection(Of Table_Addendums) = New HashSet(Of Table_Addendums)
        Public Overridable Property Table_Contract_ProjectIDforClient As Table_Contract_ProjectIDforClient
        Public Overridable Property Table_Contract_Offers As ICollection(Of Table_Contract_Offers) = New HashSet(Of Table_Contract_Offers)
        Public Overridable Property Table_Contracts_ClientAdditional As Table_Contracts_ClientAdditional
        Public Overridable Property Table_Contracts_Common As Table_Contracts_Common
        Public Overridable Property Table6_Supplier As Table6_Supplier
        Public Overridable Property Table_Contracts_UserRemarks As ICollection(Of Table_Contracts_UserRemarks) = New HashSet(Of Table_Contracts_UserRemarks)
        Public Overridable Property Table_Contract_UsersApprv As ICollection(Of Table_Contract_UsersApprv) = New HashSet(Of Table_Contract_UsersApprv)
    
    End Class

End Namespace
