'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table3_Invoice
        Public Property InvoiceID As Integer
        Public Property Invoice_No As String
        Public Property Invoice_Date As Date
        Public Property PO_No As String
        Public Property InvoiceValue As Decimal
        Public Property DeadlineToPay As Nullable(Of Date)
        Public Property Notes As String
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property CreatedBy As Nullable(Of Date)
        Public Property DeletedBy As Nullable(Of Date)
        Public Property PersonCreated As String
        Public Property PersonUpdated As String
        Public Property PersonDeleted As String
        Public Property FromAccess As Nullable(Of Integer)
        Public Property ContractReference As String
        Public Property Scenario As Nullable(Of Short)
    
        Public Overridable Property Table3_Invoice_PDF As Table3_Invoice_PDF
        Public Overridable Property Table3_Invoice_PRrequestToPM As Table3_Invoice_PRrequestToPM
        Public Overridable Property Table4_PaymentRequest As ICollection(Of Table4_PaymentRequest) = New HashSet(Of Table4_PaymentRequest)
        Public Overridable Property Table2_PONo As Table2_PONo
        Public Overridable Property Table3_Invoice_Type_Junction As ICollection(Of Table3_Invoice_Type_Junction) = New HashSet(Of Table3_Invoice_Type_Junction)
    
    End Class

End Namespace
