'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Contract_Addendum_TimeLimitApprovals
        Public Property Id As Integer
        Public Property ContractId As Integer
        Public Property AddendumId As Integer
        Public Property ActionTime As Nullable(Of Date)
        Public Property UserName As String
        Public Property Action As String
    
    End Class

End Namespace
