'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Contract_CommentsRead
        Public Property id As Integer
        Public Property C_Or_A As String
        Public Property id_comment As Integer
        Public Property FromWho As String
        Public Property ReadWho As String
        Public Property WhenRead As Date
    
    End Class

End Namespace
