'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table1_Project
        Public Property ProjectID As Short
        Public Property ProjectName As String
        Public Property ProjectManager As String
        Public Property ProjectAdress As String
        Public Property PM_email As String
        Public Property CurrentStatus As Boolean
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property FromAccess As Nullable(Of Integer)
        Public Property Type As String
        Public Property Report As Nullable(Of Boolean)
        Public Property BackUpRequired As Nullable(Of Boolean)
        Public Property InsuranceStart As Nullable(Of Date)
        Public Property InsuranceFinish As Nullable(Of Date)
        Public Property POcreate As Nullable(Of Boolean)
        Public Property CompletionDate As Nullable(Of Date)
        Public Property ContractCurrency As String
        Public Property ContractAmount As Nullable(Of Decimal)
        Public Property Margin As Nullable(Of Decimal)
        Public Property NakladnayaEnabled As Nullable(Of Boolean)
        Public Property BackColor As String
        Public Property ForeColor As String
        Public Property PendingSummary As Nullable(Of Boolean)
        Public Property ApproveRequired As Nullable(Of Boolean)
        Public Property RequestedRequired As Nullable(Of Boolean)
        Public Property DontShowContractPoAssistance As Nullable(Of Boolean)
        Public Property ChangeOrderSignedExcVAT As Nullable(Of Decimal)
        Public Property SendEmailsNonZeroBalance As Nullable(Of Boolean)
        Public Property NewGeneration As Nullable(Of Boolean)
        Public Property Logo As String
        Public Property NewPoPolicy As Nullable(Of Boolean)
        Public Property PoMakerNewGeneration As Boolean
        Public Property PR_Coverpage_Approval_Allowed As Boolean
        Public Property PR_Coverpage_Approval_Compulsory As Boolean
        Public Property PM_SignaturesLink As String
        Public Property AutoCCApproval As Nullable(Of Boolean)
        Public Property ExtraApprovalIfNoSignedClientContract As Boolean
        Public Property BudgetEmailControl As Boolean
        Public Property FrameBudgetEmailControl As Boolean
    
        Public Overridable Property Table_Budget As ICollection(Of Table_Budget) = New HashSet(Of Table_Budget)
        Public Overridable Property Table1_ProjectInsurCertf As ICollection(Of Table1_ProjectInsurCertf) = New HashSet(Of Table1_ProjectInsurCertf)
        Public Overridable Property Table2_PONo As ICollection(Of Table2_PONo) = New HashSet(Of Table2_PONo)
    
    End Class

End Namespace
