'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table8_ExchangeRates
        Public Property [Date] As Date
        Public Property RubbleDollar As Decimal
        Public Property RubbleEuro As Decimal
    
        Public Overridable Property Table5_PayLog As ICollection(Of Table5_PayLog) = New HashSet(Of Table5_PayLog)
    
    End Class

End Namespace
