'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Contracts_UserRemarks
        Public Property id As Integer
        Public Property ContractID As Integer
        Public Property UserName As String
        Public Property Remark As String
        Public Property LastUpdate As Nullable(Of Date)
    
        Public Overridable Property Table_Contracts As Table_Contracts
    
    End Class

End Namespace
