'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table6_Supplier
        Public Property SupplierID As String
        Public Property SupplierName As String
        Public Property PhoneNumber1 As String
        Public Property PhoneNumber2 As String
        Public Property FaxNumber1 As String
        Public Property FaxNumber2 As String
        Public Property WebAdress As String
        Public Property EmailAddress As String
        Public Property Adress As String
        Public Property VAT_Free As Boolean
        Public Property Notes As String
        Public Property FromAccess As Nullable(Of Integer)
        Public Property CreatedBy As Nullable(Of Date)
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property PersonCreated As String
        Public Property Discount As String
        Public Property PaymentTerms As String
        Public Property CreditAmount As String
        Public Property Client As Nullable(Of Boolean)
        Public Property SupplierNameEng As String
    
        Public Overridable Property Table6_SupplierDetails As ICollection(Of Table6_SupplierDetails) = New HashSet(Of Table6_SupplierDetails)
        Public Overridable Property Table2_PONo As ICollection(Of Table2_PONo) = New HashSet(Of Table2_PONo)
        Public Overridable Property Table_Contracts As ICollection(Of Table_Contracts) = New HashSet(Of Table_Contracts)
        Public Overridable Property Table_SupplierType_Junction As ICollection(Of Table_SupplierType_Junction) = New HashSet(Of Table_SupplierType_Junction)
    
    End Class

End Namespace
