'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_SupplierType_Junction
        Public Property id As Integer
        Public Property SupplierID As String
        Public Property SupplierTypeId As Integer
    
        Public Overridable Property Table_SupplierType As Table_SupplierType
        Public Overridable Property Table6_Supplier As Table6_Supplier
    
    End Class

End Namespace
