'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_PaymentRequest_OverHeadCheck
        Public Property PayReqNo As Integer
        Public Property WhoChecked As String
        Public Property Status As String
        Public Property WhenChecked As Nullable(Of Date)
    
    End Class

End Namespace
