'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table6_SupplierDetails
        Public Property SupplierID As String
        Public Property SupplierAdressDetails_ENG As String
        Public Property SupplierAdressDetails_RUS As String
        Public Property SupplierBankDetails_ENG As String
        Public Property SupplierBankDetails_RUS As String
    
        Public Overridable Property Table6_Supplier As Table6_Supplier
    
    End Class

End Namespace
