'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Approval_Scenario
        Public Property Scenario As Short
        Public Property Description As String
    
        Public Overridable Property Table_Approval_Scn_Prj_Users As ICollection(Of Table_Approval_Scn_Prj_Users) = New HashSet(Of Table_Approval_Scn_Prj_Users)
    
    End Class

End Namespace
