'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Budget
        Public Property BudgetID As Integer
        Public Property ProjectID As Short
        Public Property CostCode As String
        Public Property Budget As Nullable(Of Decimal)
        Public Property PlannedToSpend As Nullable(Of Decimal)
        Public Property PlannedToSpendCO As Nullable(Of Decimal)
        Public Property Currency As String
        Public Property UpdatedPlannedRevenue As Nullable(Of Decimal)
        Public Property OriginalBOQ As Nullable(Of Decimal)
        Public Property VCO As Nullable(Of Decimal)
        Public Property CostToGoBOQ As Nullable(Of Decimal)
        Public Property CostToGoVCO As Nullable(Of Decimal)
        Public Property Recovery As Nullable(Of Decimal)
        Public Property OriginalSelling As Nullable(Of Decimal)
    
        Public Overridable Property Table7_CostCode As Table7_CostCode
        Public Overridable Property Table1_Project As Table1_Project
    
    End Class

End Namespace
