'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Addendums_ClientAdditional
        Public Property AddendumID As Integer
        Public Property CompletionDate As Nullable(Of Date)
        Public Property AktOfWork As Boolean
        Public Property LinkToAktOfWork As String
        Public Property AktOfWorkWhen As Nullable(Of Date)
    
        Public Overridable Property Table_Addendums As Table_Addendums
    
    End Class

End Namespace
