'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_SupplierType_Tags
        Public Property TagId As Integer
        Public Property TagSourceIndex As String
        Public Property SourceType As String
        Public Property SupplierTypeId As Integer
    
        Public Overridable Property Table_SupplierType As Table_SupplierType
    
    End Class

End Namespace
