'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Contract_Offers
        Public Property ContractID As Integer
        Public Property SupplierID As String
        Public Property OfferValueWithVAT As Decimal
        Public Property Currency As String
        Public Property Attachment As String
    
        Public Overridable Property Table_Contracts As Table_Contracts
    
    End Class

End Namespace
