'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table3_Invoice_PRrequestToPM
        Public Property InvoiceID As Integer
        Public Property SiteReqNo As String
        Public Property WhoRequested As String
        Public Property ApprovedOrNot As Boolean
        Public Property WhenApproved As Nullable(Of Date)
        Public Property WhoApproved As String
        Public Property PayReqDate As Nullable(Of Date)
    
        Public Overridable Property Table3_Invoice As Table3_Invoice
    
    End Class

End Namespace
