'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Approval_PositionEmployee
        Public Property PositionID As Short
        Public Property PositionName As String
        Public Property Rank As Short
    
        Public Overridable Property Table_Approval_UserPositionPrjJunction As ICollection(Of Table_Approval_UserPositionPrjJunction) = New HashSet(Of Table_Approval_UserPositionPrjJunction)
    
    End Class

End Namespace
