'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Survey_OfficeParty
        Public Property Id As Integer
        Public Property Name_Surname As String
        Public Property Name_Surname_Russian As String
        Public Property Email As String
        Public Property Sex As String
        Public Property Pass As String
        Public Property Response As String
        Public Property LastUpdate As Nullable(Of Date)
        Public Property LastLogIn As Nullable(Of Date)
        Public Property MoneyCanAfford As Nullable(Of Integer)
        Public Property Remarks As String
    
    End Class

End Namespace
