'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table5_PayLog
        Public Property PayReqNo As Integer
        Public Property FinanceNo As String
        Public Property PaymentDate As Date
        Public Property Amount As Decimal
        Public Property Currency As String
        Public Property Note As String
        Public Property RubbleDollar As Decimal
        Public Property RubbleEuro As Decimal
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property CreatedBy As Nullable(Of Date)
        Public Property DeletedBy As Nullable(Of Date)
        Public Property PersonCreated As String
        Public Property PersonUpdated As String
        Public Property PersonDeleted As String
        Public Property Nakladnaya As Boolean
        Public Property Nakladnaya_EnteredWhen As Nullable(Of Date)
        Public Property Akt As Boolean
        Public Property Akt_EnteredWhen As Nullable(Of Date)
        Public Property ShotFaktura As Boolean
        Public Property ShotFaktura_EnteredWhen As Nullable(Of Date)
        Public Property Var1Required As Boolean
        Public Property Nak_Akt_Notes As String
        Public Property Status As Short
        Public Property StatusNote As String
        Public Property GetCollection As Nullable(Of Decimal)
        Public Property CollectedValue As Nullable(Of Decimal)
        Public Property CollectionHistory As String
        Public Property FromAccess As Nullable(Of Integer)
    
        Public Overridable Property Table4_PaymentRequest As Table4_PaymentRequest
        Public Overridable Property Table8_ExchangeRates As Table8_ExchangeRates
    
    End Class

End Namespace
