'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table7_CostCode
        Public Property CostCode As String
        Public Property CostVidisionID As String
        Public Property CodeDescription As String
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property DataCenter As Nullable(Of Boolean)
        Public Property FromAccess As Nullable(Of Integer)
        Public Property Type As String
        Public Property Note As String
    
        Public Overridable Property Table_Budget As ICollection(Of Table_Budget) = New HashSet(Of Table_Budget)
        Public Overridable Property Table2_PONo As ICollection(Of Table2_PONo) = New HashSet(Of Table2_PONo)
        Public Overridable Property Table7_CostDivision As Table7_CostDivision
    
    End Class

End Namespace
