'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_SupplierType
        Public Property SupplierTypeId As Integer
        Public Property SupplierType As String
        Public Property SupplierDiscipline As String
    
        Public Overridable Property Table_SupplierType_Junction As ICollection(Of Table_SupplierType_Junction) = New HashSet(Of Table_SupplierType_Junction)
        Public Overridable Property Table_SupplierType_Tags As ICollection(Of Table_SupplierType_Tags) = New HashSet(Of Table_SupplierType_Tags)
    
    End Class

End Namespace
