'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Approval_UserPositionPrjJunction
        Public Property id As Integer
        Public Property UserName As String
        Public Property PositionID As Short
        Public Property ProjectID As Short
    
        Public Overridable Property Table_Approval_PositionEmployee As Table_Approval_PositionEmployee
    
    End Class

End Namespace
