'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table2_PONo
        Public Property PO_No As String
        Public Property Project_ID As Short
        Public Property SupplierID As String
        Public Property Description As String
        Public Property TotalPrice As Decimal
        Public Property PO_Currency As String
        Public Property VATpercent As Decimal
        Public Property CostCode As String
        Public Property Notes As String
        Public Property PO_Date As Date
        Public Property CreatedBy As Nullable(Of Date)
        Public Property UpdatedBy As Nullable(Of Date)
        Public Property DeletedBy As Nullable(Of Date)
        Public Property PersonCreated As String
        Public Property PersonUpdated As String
        Public Property PersonDeleted As String
        Public Property FromAccess As Nullable(Of Short)
        Public Property Approved As Nullable(Of Boolean)
        Public Property PersonApproved As String
        Public Property RequestedBy As String
        Public Property CO As Boolean
        Public Property Scenario As Short
        Public Property FrameContractPO As Boolean
        Public Property FrameContractID As Integer
    
        Public Overridable Property Table_PO_Akt As ICollection(Of Table_PO_Akt) = New HashSet(Of Table_PO_Akt)
        Public Overridable Property Table_PO_Nakladnaya As ICollection(Of Table_PO_Nakladnaya) = New HashSet(Of Table_PO_Nakladnaya)
        Public Overridable Property Table6_Supplier As Table6_Supplier
        Public Overridable Property Table7_CostCode As Table7_CostCode
        Public Overridable Property Table3_Invoice As ICollection(Of Table3_Invoice) = New HashSet(Of Table3_Invoice)
        Public Overridable Property Table1_Project As Table1_Project
    
    End Class

End Namespace
