'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table_Approval_Scn_Prj_Users
        Public Property id As Integer
        Public Property UserName As String
        Public Property Scenario As Short
        Public Property ProjectID As Short
        Public Property ToleratedDay As Integer
    
        Public Overridable Property Table_Approval_Scenario As Table_Approval_Scenario
    
    End Class

End Namespace
