'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class Table1_ProjectInsurCertf
        Public Property id As Integer
        Public Property ProjectID As Short
        Public Property Remarks As String
        Public Property InsuranceStart As Nullable(Of Date)
        Public Property InsuranceFinish As Nullable(Of Date)
        Public Property DocumentReference As String
    
        Public Overridable Property Table1_Project As Table1_Project
    
    End Class

End Namespace
