'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_ContractsAddendumsNonExecutedTotal
        Public Property id As System.Guid
        Public Property ProjectID As Short
        Public Property CostCode As String
        Public Property TotalNotExcecutedValueExcVAT_Rub As Nullable(Of Decimal)
        Public Property TotalNotExcecutedValueExcVAT_Euro As Nullable(Of Decimal)
        Public Property TotalNotExcecutedValueExcVAT_Dollar As Nullable(Of Decimal)
    
    End Class

End Namespace
