'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_WhatToBePaidRevised
        Public Property Id As System.Guid
        Public Property SupplierName As String
        Public Property Description As String
        Public Property PO_No As String
        Public Property Invoice_No As String
        Public Property Invoice_Date As Date
        Public Property Wo_VAT As Nullable(Of Decimal)
        Public Property PO_Currency As String
        Public Property WithVAT As Nullable(Of Decimal)
        Public Property PayReqNo As Integer
        Public Property [Date] As Date
        Public Property LinkToInvoice As String
        Public Property Approved As String
        Public Property ProjectID As Short
        Public Property RubbleDollar As Decimal
        Public Property RubbleEuro As Decimal
    
    End Class

End Namespace
