'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_AddendumDetails
        Public Property Id As System.Guid
        Public Property AddendumID As Integer
        Public Property ProjectNameTitle As String
        Public Property ProjectName As String
        Public Property PoNoTitle As String
        Public Property PO_No As String
        Public Property SupplierNameTitle As String
        Public Property SupplierName As String
        Public Property AddendumTypeTitle As String
        Public Property AddendumType As String
        Public Property ContractNoTitle As String
        Public Property ContractNo As String
        Public Property ContractDateTitle As String
        Public Property ContractDate As String
        Public Property ContractValueTitle As String
        Public Property ContractValue_withVAT As String
        Public Property ContractCurrencyTitle As String
        Public Property ContractCurrency As String
        Public Property ContractTypeTitle As String
        Public Property ContractType As String
        Public Property ContractDescriptionTitle As String
        Public Property ContractDescription As String
        Public Property CostCodeTitle As String
        Public Property CodeDescription As String
        Public Property AddnNoTitle As String
        Public Property AddendumNo As String
        Public Property AddnDateTitle As String
        Public Property AddendumDate As String
        Public Property AddendumValueTitle As String
        Public Property AddendumValue_WithVAT As String
        Public Property VATpercentTitle As String
        Public Property VATpercent As Nullable(Of Short)
        Public Property BudgetValueWithVATTitle As String
        Public Property Budget As String
        Public Property RequestedByTitle As String
        Public Property RequestedBy As String
        Public Property PenaltyToMercuryTitle As String
        Public Property Penalties As String
        Public Property PenaltyToSupplierTitle As String
        Public Property PenaltiesToSupplier As String
        Public Property DeliveryTermsTitle As String
        Public Property DeliveryTerms As String
        Public Property AddnDescriptionTitle As String
        Public Property AddendumDescription As String
        Public Property StartDateTitle As String
        Public Property StartDate As String
        Public Property FinishDateTitle As String
        Public Property FinishDate As String
        Public Property AdvanceTitle As String
        Public Property Advance As String
        Public Property InterimTitle As String
        Public Property Interim As String
        Public Property ShipmentTitle As String
        Public Property Shipment As String
        Public Property DeliveryTitle As String
        Public Property Delivery As String
        Public Property RetentionTitle As String
        Public Property Retention As String
        Public Property PenallyToMercuryNoteTitle As String
        Public Property PenaltiesNote As String
        Public Property PenaltyToSupplierNoteTitle As String
        Public Property PenaltiesToSupplierNote As String
        Public Property GuaranteePeriodTitle As String
        Public Property GuaranteePeriod As String
        Public Property CreationInfo As String
        Public Property CompletionDateTitle As String
        Public Property CompletionDate As String
        Public Property AktOfWorkTitle As String
        Public Property AktOfWork As String
    
    End Class

End Namespace
