'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_FrameContractsBudgetStatus
        Public Property Id As System.Guid
        Public Property ProjectID As Short
        Public Property SupplierName As String
        Public Property ContractNo As String
        Public Property ContractDate As Nullable(Of Date)
        Public Property ContractID As Integer
        Public Property BudgetWithVAT As Decimal
        Public Property TotalPoWithVAT As Decimal
        Public Property AvailableBudgetForNewPoWithVAT As Nullable(Of Decimal)
    
    End Class

End Namespace
