'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_CheckTolerance
        Public Property Id As System.Guid
        Public Property ContractID As Integer
        Public Property AddendumId As Integer
        Public Property UserName As String
        Public Property ProjectID As Short
        Public Property Scenario As Short
        Public Property CreatedBy As Nullable(Of Date)
        Public Property C_Now As Date
        Public Property ToleratedDay As Integer
        Public Property DayDiff As Nullable(Of Integer)
        Public Property CheckTolerance As Nullable(Of Integer)
    
    End Class

End Namespace
