'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_PaymentRequestApprovalStatus
        Public Property Id As System.Guid
        Public Property ProjectID As Short
        Public Property ProjectName As String
        Public Property ApprovalRequiredPersons As String
        Public Property InvoiceID As Integer
        Public Property ApprovedOrNot As Integer
        Public Property Position As String
        Public Property email As String
    
    End Class

End Namespace
