'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_ContractFilesMoveDOC
        Public Property Id As System.Guid
        Public Property LastSlash As Nullable(Of Integer)
        Public Property LastDot As Nullable(Of Integer)
        Public Property Path1 As String
        Public Property CreateFolder As String
        Public Property Path2 As String
        Public Property extension As String
        Public Property FileNameItself As String
        Public Property ContractID As Integer
    
    End Class

End Namespace
