'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_PendingListRev1
        Public Property ProjectName As String
        Public Property PayReqDate As Date
        Public Property Urgency As String
        Public Property Invoice_Date As Date
        Public Property Invoice_No As String
        Public Property SiteRecordNo As String
        Public Property PO_Currency As String
        Public Property SupplierName As String
        Public Property Description As String
        Public Property LinkToInvoice As String
        Public Property ProjectID As Short
        Public Property Approved As String
        Public Property PersonApprove As String
        Public Property SupplierID As String
        Public Property PersonCreated As String
        Public Property AttachmentChange As Nullable(Of Boolean)
        Public Property AttachmentChangeWhen As Nullable(Of Date)
        Public Property PersonChangedAttachment As String
        Public Property AttachmentExist As Nullable(Of Boolean)
        Public Property PoTotalWithVAT As Nullable(Of Decimal)
        Public Property TotalPaidWithVAT As Nullable(Of Decimal)
        Public Property TotalBalanceWithVAT As Nullable(Of Decimal)
        Public Property OrderCurrency As Nullable(Of Integer)
        Public Property PendingWithVAT As Nullable(Of Decimal)
        Public Property Diff_Paid_Collect As Nullable(Of Decimal)
        Public Property Percantage_To_Paid As Nullable(Of Decimal)
        Public Property PO_No As String
        Public Property BalanceAfterPending As Nullable(Of Decimal)
        Public Property PayReqNo As Integer
        Public Property ApproveNewGen As Nullable(Of Boolean)
        Public Property PrintPDF As Nullable(Of Boolean)
        Public Property InvoiceID As Integer
        Public Property CreatedByPaymentRequest As Nullable(Of Date)
    
    End Class

End Namespace
