'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace PTS_MERCURY.db

    Partial Public Class View_CostCodeSummary0
        Public Property Id As System.Guid
        Public Property ProjectID As Short
        Public Property CostCodeAlias As String
        Public Property CostCode As String
        Public Property CostCode1 As String
        Public Property CostCode2 As String
        Public Property TotalDollarPendingExcVAT As Nullable(Of Decimal)
        Public Property TotalEuroPendingExcVAT As Nullable(Of Decimal)
        Public Property TotalRublePendingExcVAT As Nullable(Of Decimal)
        Public Property TotalDollarPaidExcVAT As Nullable(Of Decimal)
        Public Property TotalEuroPaidExcVAT As Nullable(Of Decimal)
        Public Property TotalRublePaidExcVAT As Nullable(Of Decimal)
        Public Property TotalPoTotalDollarExcVAT As Nullable(Of Decimal)
        Public Property TotalPoTotalEuroExcVAT As Nullable(Of Decimal)
        Public Property TotalPoTotalRubleExcVAT As Nullable(Of Decimal)
        Public Property TotalBalanceDollarExcVAT As Nullable(Of Decimal)
        Public Property TotalBalanceEuroExcVAT As Nullable(Of Decimal)
        Public Property TotalBalanceRubleExcVAT As Nullable(Of Decimal)
        Public Property TotalCollectedDocDollarExcVAT As Nullable(Of Decimal)
        Public Property TotalCollectedDocEuroExcVAT As Nullable(Of Decimal)
        Public Property TotalCollectedDocRubleExcVAT As Nullable(Of Decimal)
    
    End Class

End Namespace
